import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import GoogleAuthProvider from '@/provider/GoogleAuthProvider';
import StoreProvider from '@/provider/StoreProvider';
import Spinner from '@/components/Spinner';
import ReactQueryProvider from '@/provider/ReactQueryProvider';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Toaster />
				<GoogleAuthProvider>
					<StoreProvider>
						<ReactQueryProvider>{children}</ReactQueryProvider>
						<Spinner />
					</StoreProvider>
				</GoogleAuthProvider>
			</body>
		</html>
	);
}
